# Digital Ocean App Platform Specification
# LeadScout Production Deployment

name: leadscout-production
region: fra  # Frankfurt - change to nyc, sfo, sgp, etc. as needed

# Static Site Configuration (Next.js)
static_sites:
  - name: leadscout-web
    github:
      repo: YOUR_GITHUB_USERNAME/leadscout  # UPDATE THIS
      branch: main
      deploy_on_push: true

    # Build configuration
    build_command: cd leadscout-web && npm ci && npm run build
    output_dir: leadscout-web/.next

    # Environment variables for build
    envs:
      # Node.js environment
      - key: NODE_ENV
        value: "production"

      # Application URLs
      - key: NEXT_PUBLIC_APP_URL
        value: "https://leadscout-production.ondigitalocean.app"  # Update with custom domain if applicable
        type: SECRET

      # Clerk Authentication (REQUIRED)
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        value: "REPLACE_WITH_PRODUCTION_CLERK_PUBLISHABLE_KEY"
        type: SECRET

      - key: CLERK_SECRET_KEY
        value: "REPLACE_WITH_PRODUCTION_CLERK_SECRET_KEY"
        type: SECRET

      - key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
        value: "/sign-in"

      - key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
        value: "/sign-up"

      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
        value: "/dashboard"

      - key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
        value: "/onboarding"

      # Convex Backend (REQUIRED)
      - key: NEXT_PUBLIC_CONVEX_URL
        value: "REPLACE_WITH_PRODUCTION_CONVEX_URL"
        type: SECRET

      - key: CONVEX_DEPLOY_KEY
        value: "REPLACE_WITH_CONVEX_DEPLOY_KEY"
        type: SECRET

      # Stripe Payments (REQUIRED - Use LIVE keys for production)
      - key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
        value: "REPLACE_WITH_STRIPE_LIVE_PUBLISHABLE_KEY"
        type: SECRET

      - key: STRIPE_SECRET_KEY
        value: "REPLACE_WITH_STRIPE_LIVE_SECRET_KEY"
        type: SECRET

      - key: STRIPE_WEBHOOK_SECRET
        value: "REPLACE_WITH_STRIPE_WEBHOOK_SECRET"
        type: SECRET

      # Stripe Price IDs (REQUIRED - Create in Stripe Dashboard)
      - key: NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID
        value: "REPLACE_WITH_STARTER_PLAN_PRICE_ID"
        type: SECRET

      - key: NEXT_PUBLIC_STRIPE_GROWTH_PRICE_ID
        value: "REPLACE_WITH_GROWTH_PLAN_PRICE_ID"
        type: SECRET

      - key: NEXT_PUBLIC_STRIPE_SCALE_PRICE_ID
        value: "REPLACE_WITH_SCALE_PLAN_PRICE_ID"
        type: SECRET

      - key: STRIPE_CREDIT_PRICE_ID
        value: "REPLACE_WITH_CREDIT_PRICE_ID"
        type: SECRET

      # Resend Email (REQUIRED)
      - key: RESEND_API_KEY
        value: "REPLACE_WITH_RESEND_API_KEY"
        type: SECRET

      - key: RESEND_FROM_EMAIL
        value: "noreply@leadscout.app"  # Update with verified domain

      # Business Logic Configuration
      - key: PAYOUT_MINIMUM_THRESHOLD
        value: "20"

      - key: PLATFORM_COMMISSION_RATE
        value: "0.5"

      - key: STARTER_PLAN_CREDITS
        value: "20"

      - key: GROWTH_PLAN_CREDITS
        value: "60"

      - key: SCALE_PLAN_CREDITS
        value: "150"

    # Routes configuration
    routes:
      - path: /

    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3

    # Instance configuration
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/month - upgrade to basic-xs, basic-s, etc. as needed

# CORS and security headers are configured in next.config.ts

# For custom domain configuration, add:
# domains:
#   - domain: leadscout.app
#     type: PRIMARY
#   - domain: www.leadscout.app
#     type: ALIAS
